# 此工作流程将使用节点运行测试，然后在创建版本时将包发布到 GitHub Packages
#相关更多信息，请参阅：https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

名称：Node.js包

于：
  发布：
    类型：[已创建]

职位：
  构建：
    运行：ubuntu-latest
    步骤：
      - 用途：actions/checkout@v3
      - 用途：actions/setup-node@v3
        与：
          节点版本：16
      -运行：npm ci
      -运行：npm test

  发布gpr：
    需求： 满足
    运行：ubuntu-latest
    权限：
      内容：阅读
      套餐：写
    步骤：
      - 用途：actions/checkout@v3
      -用途：actions/setup-node@v3
        与：
          节点版本：16
          注册表 URL :注册表网址：https://npm.pkg.github.com/: //npm.pkg.github.com/
      -运行：npm ci
      -运行：npm 发布
        环境：
NODE_AUTH_TOKEN：$ Secrets.GITHUB_TOKEN { {   { Secrets.GITHUB_TOKEN } }
